### ISSUE TITLE
Example in high frequency

### ISSUE THREAD

**Issue by mcardenass** [Priyanshurgupta/Group_velocity_dispersion_using_Superlets#1]
I am trying to calculate the dispersion curve for a cross-correlation function between two stations that are 0.138 km apart. The sampling interval is 50 Hz and the signal has 201 points. I can't find the relationship between the frequency distribution and the sampling frequency of the scalogram that would allow me to define the dispersion curve. Could you help me calculate that curve and visualize the scatter plot, either with the wavelet_transform or superlits? Here is part of my modification to the code, and I'm sending you my signal in sac format. Thank you in advance

############# Plot seismogram ############
from obspy.core import read
s=read(r"rec01_rec40.stk")
header=s[0].stats
distance=header.sac['dist']
fs=round(1/header.sac['delta'])
signal=s[0].data
print(distance,fs,len(signal))
fig, ax = plt.subplots(figsize=(15, 2), dpi=300)
ax.set_xlabel("Time (s)")
ax.plot(jnp.linspace(0, len(signal)/fs, len(signal)), signal)

####### Code to plot dispersion image of the seismogram (add discretization to improve quality of dispersion images)##
velocity=np.zeros(len(signal))
freqs = jnp.linspace(0.1, 250, 150)
#print(freqs)
import os
import numpy as np

for k in range(len(signal), 0, -1):
    velocity[len(signal)-k-1]=(distance)/(k/fs)
#print(velocity)

fig, ax = plt.subplots(ncols=3, figsize=(15, 5), dpi=300)

for i, c in enumerate([3,16,33]):
    scalogram = wavelet_transform(signal, freqs, c, fs*1000)
    #arr=[]
    points=np.zeros(len(freqs))
    for n in range (0,len(freqs)):
        amplitude=20*(np.log10(np.abs(scalogram[n])))
        points[n]=points[n]+np.argmax(np.abs(scalogram[n]))

    vg=distance/((points/fs)+0.02)
    
    np.savetxt('curve.txt', vg, fmt='%.3f', newline=os.linesep)   
    
    ax[i].plot(freqs[:19], vg[:19], 'w--')
    ax[i].contourf(freqs, velocity, np.log10(np.abs(scalogram).T)[::-1], cmap="jet", origin="lower")
    ax[i].set_title(f"Cycles: {c}")
    ax[i].set_xlabel("Frequency (Hz)")
    ax[i].set_ylabel("Group Velocity(km/s)")
    ax[i].set_ylim(0.1,1)
    ax[i].set_xticks([50, 100, 150, 200, 250], [5, 10, 15, 20, 25]) 

m = plt.cm.ScalarMappable(cmap='jet')
m.set_array(np.log10(np.abs(scalogram)))
m.set_clim(0, 1)
myticks = np.arange(0, 1, 10)
cbar=plt.colorbar(m, ax=ax.ravel().tolist(), boundaries=np.linspace(0, 1, 100), ticks=[0, .1, .2, .3, .4,.5,.6,.7,.8,.9, 1],pad=.03, aspect=28)
cbar.ax.tick_params(labelsize=9, direction='out')
plt.show()

[rec01_rec40.stk.zip](https://github.com/user-attachments/files/17501668/rec01_rec40.stk.zip)

**Comment by Priyanshurgupta** [comment]
I have observed that your data have dominant spectrum in the frequency range of 1-10 Hz, where it is likely to disperse. I have shown the dispersion curve for your data. Please see the code attached.
I hope this helps.  
[high_frequency_query.zip](https://github.com/user-attachments/files/17508436/high_frequency_query.zip)

**Comment by mcardenass** [comment]
Thank you very much, it's working now.
